### ISSUE TITLE
Pins for 2.9 inch ?

### ISSUE THREAD

**Issue by hiteshjoshi** [wiless/waveshare#1]
How do I make this work on this display?

https://www.waveshare.com/wiki/2.9inch_e-Paper_Module_(B)

**Comment by hiteshjoshi** [comment]
sorry, I don't think it's your library. Guess your dependent library embd works till raspberry 2 but not 3?

**Comment by wiless** [comment]
There is minor tweak done to the embd for making it work on pi3.

**Comment by wiless** [comment]
What do you mean by "its not your library" ? which library

**Comment by Sciroccogti** [comment]
Well I also wonder which kind of e-paper can this repo can drive.

**Comment by wiless** [comment]
> Well I also wonder which kind of e-paper can this repo can drive.

This was written for the waveshare module

**Comment by Sciroccogti** [comment]
> This was written for the waveshare module

Yes, but does it work on other size of waveshare e-paper? For example, the 2.9 inch one?
